// Quiz Data - 40 questions for entrance exam
export const quizData = [
  // I. PRONUNCIATION (1.0 điểm)
  { id: 1, type: 'mcq', question: "Choose the word whose underlined part is pronounced differently: house, cloud, group, mouth", options: ["house", "cloud", "group", "mouth"], answer: 2, explain: "'group' phát âm /ɡruːp/ (ou = /uː/)\nCác từ khác: /aʊ/", translate: "Phát âm khác: group" },
  { id: 2, type: 'mcq', question: "Choose the word whose underlined part is pronounced differently: needed, happened, wanted, included", options: ["needed", "happened", "wanted", "included"], answer: 1, explain: "'needed' phát âm /ˈniːdɪd/\nCác từ khác: /ɪd/", translate: "Phát âm khác: needed" },
  { id: 3, type: 'mcq', question: "Choose the word whose underlined part is pronounced differently: heavy, honest, happy, healthy", options: ["heavy", "honest", "happy", "healthy"], answer: 1, explain: "'honest' phát âm /ˈɒnɪst/ (on = /ɒ/)\nCác từ khác: /ɛ/ hoặc /æ/", translate: "Phát âm khác: honest" },
  { id: 4, type: 'mcq', question: "Choose the word whose underlined part is pronounced differently: sign, high, ship, mind", options: ["sign", "high", "ship", "mind"], answer: 2, explain: "'ship' phát âm /ʃɪp/ (i = /ɪ/)\nCác từ khác: /aɪ/", translate: "Phát âm khác: ship" },

  // II. GRAMMAR & VOCABULARY (2.0 điểm)
  { id: 5, type: 'mcq', question: "While I ________ to school yesterday, I met my old friend from primary school.", options: ["walk", "am walking", "was walking", "have walked"], answer: 2, explain: "Thì quá khứ tiếp diễn: While + was/were + V-ing\nDiễn tả hành động đang xảy ra bị ngắt", translate: "Quá khứ tiếp diễn" },
  { id: 6, type: 'mcq', question: "She is very fond ________ collecting stamps and old coins.", options: ["in", "at", "of", "with"], answer: 2, explain: "Cụm từ: be fond of = thích, yêu thích", translate: "Giới từ: of" },
  { id: 7, type: 'mcq', question: "If he ________ speaking English every day, he can improve his English pronunciation.", options: ["practises", "will practice", "could practise", "practised"], answer: 0, explain: "Câu điều kiện loại 1: If + hiện tại đơn, will + V\nPractises (hiện tại) → will improve", translate: "Điều kiện loại 1" },
  { id: 8, type: 'mcq', question: "That's the man ________ helped me fix my bike last week.", options: ["which", "who", "where", "whose"], answer: 1, explain: "Đại từ quan hệ: who (người), which (vật)\nWhere (nơi), whose (sở hữu)", translate: "Đại từ quan hệ: who" },
  { id: 9, type: 'mcq', question: "The countryside is much ________ than the city, so many people want to move there.", options: ["noisier", "more peaceful", "busier", "more polluted"], answer: 1, explain: "So sánh hơn: more + tính từ dài\nPeaceful phù hợp với countryside", translate: "So sánh hơn" },
  { id: 10, type: 'mcq', question: "The meeting was delayed because the manager's car ________ on the way to the office.", options: ["broke down", "broke into", "broke off", "broke out"], answer: 0, explain: "Phrasal verb: break down = hỏng máy\nBreak into: đột nhập, off: dừng, out: bùng nổ", translate: "Phrasal verb" },
  { id: 11, type: 'mcq', question: "The students felt very ________ after taking the long and difficult exam.", options: ["exhausted", "exciting", "amazed", "boring"], answer: 0, explain: "Exhausted = mệt mỏi, kiệt sức\nPhù hợp sau kỳ thi khó", translate: "Mệt mỏi" },
  { id: 12, type: 'mcq', question: "Mary: 'Could you please show me the way to the post office?' - Tom: '________'", options: ["Yes, it's over there, on your left", "Thank you very much", "No, I couldn't", "Yes, I'm fine"], answer: 0, explain: "Trả lời yêu cầu lịch sự: chỉ đường\nThank you không phải trả lời", translate: "Hội thoại" },

  // III. WORD FORM (1.0 điểm)
  { id: 13, type: 'mcq', question: "My friends are interested in the ________ beauty of Ha Long Bay. (NATURE)", options: ["nature", "natural", "naturally", "naturalist"], answer: 1, explain: "Nature (danh từ) → natural (tính từ)", translate: "Tính từ" },
  { id: 14, type: 'mcq', question: "Last week, we ________ a lot of old books for disadvantaged children. (COLLECTION)", options: ["collect", "collected", "collection", "collective"], answer: 1, explain: "Collect (động từ) → collected (quá khứ)", translate: "Quá khứ" },
  { id: 15, type: 'mcq', question: "My sister is wearing a T-shirt of the latest model. She always dresses ________. (FASHIONABLE)", options: ["fashion", "fashionable", "fashionably", "unfashionable"], answer: 2, explain: "Fashionable (tính từ) → fashionably (trạng từ)", translate: "Trạng từ" },
  { id: 16, type: 'mcq', question: "Watching TV is a popular form of ________. (ENTERTAIN)", options: ["entertain", "entertaining", "entertainment", "entertainer"], answer: 2, explain: "Entertain (động từ) → entertainment (danh từ)", translate: "Danh từ" },

  // IV. READING CLOZE (1.5 điểm)
  { 
    id: 17, 
    type: 'mcq',
    passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", 
    question: "Choose the best word for blank (1): Technology ________ an important part of modern life.", 
    options: ["is", "are", "was", "were"], 
    answer: 0, 
    explain: "Technology là danh từ số ít, dùng 'is'", 
    translate: "Công nghệ là" 
  },
  { id: 18, type: 'mcq', passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", question: "Choose the best word for blank (2): smartphones, ________ connect them to vast networks...", options: ["which", "who", "where", "when"], answer: 0, explain: "'which' dùng để nối mệnh đề quan hệ cho vật", translate: "Mà kết nối" },
  { id: 19, type: 'mcq', passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", question: "Choose the best word for blank (3): people ________ letters or relied on slow telephone calls...", options: ["send", "will send", "sent", "have sent"], answer: 2, explain: "Thời quá khứ: a few decades ago", translate: "Gửi thư" },
  { id: 20, type: 'mcq', passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", question: "Choose the best word for blank (4): makes the process of learning ________ than ever before...", options: ["easier", "easy", "less easy", "the easiest"], answer: 0, explain: "So sánh hơn: easier than ever", translate: "Dễ hơn" },
  { id: 21, type: 'mcq', passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", question: "Choose the best word for blank (5): everyone ________ to consciously balance their online engagements...", options: ["have", "has", "having", "had"], answer: 1, explain: "Everyone là số ít, dùng 'has'", translate: "Phải" },
  { id: 22, type: 'mcq', passage: "Technology (1) ________ an important part of modern life. Indeed, the rapid advancements we see daily mean that many people simply can't imagine navigating a day without their smartphones, (2) ________ connect them to vast networks of information and communication across the globe. Just a few decades ago, people (3) ________ letters or relied on slow telephone calls to communicate; now, the simple tap of a finger allows them to send a message, share a photo, or video call anyone instantly. Furthermore, technology also makes the process of learning (4) ________ than ever before, largely because students can access a boundless ocean of educational resources and current information online. However, we must acknowledge the downside: excessive screen time can seriously harm our physical and mental health. Therefore, everyone (5) ________ to consciously balance their online engagements with offline activities, such as exercise or spending time with family. If we (6) ________ to use technology wisely and intentionally, it will make our lives significantly better.", question: "Choose the best word for blank (6): If we ________ to use technology wisely...", options: ["deny", "refuse", "manage", "succeed"], answer: 2, explain: "'manage' = có thể, phù hợp nghĩa", translate: "Quản lý" },

  // V. READING COMPREHENSION (1.5 điểm)
  { 
    id: 23, 
    type: 'mcq',
    passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", 
    question: "What is the main idea of the passage?", 
    options: ["Teenagers should focus only on doing exercise.", "Teenagers are too busy to care about their health.", "Adults should teach teens how to eat properly.", "Good health for teens depends on combined factors."], 
    answer: 3, 
    explain: "Ý chính: Đoạn văn đề cập ngủ, ăn uống, tập thể dục", 
    translate: "Ý chính" 
  },
  { id: 24, type: 'mcq', passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", question: "The word 'concentrate' in paragraph 2 is closest in meaning to", options: ["relax", "focus", "sleep", "talk"], answer: 1, explain: "Concentrate = tập trung = focus", translate: "Từ vựng" },
  { id: 25, type: 'mcq', passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", question: "The word 'It' in paragraph 4 refers to", options: ["exercise", "food", "health", "diet"], answer: 0, explain: "'It' thay thế cho 'exercise' ở câu trước", translate: "Thay thế" },
  { id: 26, type: 'mcq', passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", question: "According to the passage, what do many teens do because they are in a hurry?", options: ["Sleep more hours", "Skip breakfast", "Drink a lot of water", "Avoid using phones"], answer: 1, explain: "Văn bản: skip breakfast...in a hurry", translate: "Chi tiết" },
  { id: 27, type: 'mcq', passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", question: "What do experts suggest about sleep?", options: ["Teens should sleep for six hours.", "Teens should sleep for about eight to ten hours.", "Teens should stay up late for homework.", "Teens should use their phones before sleeping."], answer: 1, explain: "Văn bản: 8-10 hours each night", translate: "Chi tiết" },
  { id: 28, type: 'mcq', passage: "Teenagers today are busier than ever. Between school, homework, part-time jobs, and social media, many teens find it difficult to live a healthy lifestyle. However, staying healthy during these years is extremely important. Good habits built in adolescence often continue into adulthood. Experts say that teenagers should sleep for about eight to ten hours every night. Unfortunately, most teens get only six or seven hours of sleep. Lack of sleep can make it hard to concentrate in class and can even lead to stress or mood problems. To stay healthy, teens should avoid using their phones late at night and try to go to bed at the same time every day. Eating habits are another key part of health. Many young people skip breakfast or eat fast food because they are in a hurry. Nutritionists suggest that a balanced diet should include fruits, vegetables, whole grains, and enough water. Exercise is also important. Teens should do at least 60 minutes of physical activity each day. It could be walking, playing sports, or simply dancing to music. Staying active helps not only the body but also the mind. Healthy living isn't about being perfect; it's about making small, smart choices every day.", question: "Which of the following statements is TRUE?", options: ["Exercise only helps the body, not the mind.", "Teens should eat more fast food to save time and have more energy.", "Staying active is good for both body and mind.", "Communities become stronger when people care for each other."], answer: 2, explain: "Văn bản: helps body and mind", translate: "Chi tiết" },

  // VI. ERROR IDENTIFICATION (1.0 điểm)
  { id: 29, type: 'mcq', question: "Identify the mistake: The students were very 'excite' when they heard the good news about their exam results.", options: ["students", "excite", "heard", "news"], answer: 1, explain: "Excite (động từ) → excited (tính từ) sau 'were'", translate: "Lỗi từ loại" },
  { id: 30, type: 'mcq', question: "Identify the mistake: He 'has went' to Ha Long Bay twice this year with his family.", options: ["has went", "to", "twice", "this year"], answer: 0, explain: "Go: went (quá khứ) → gone (quá khứ phân từ)", translate: "Động từ bất quy tắc" },
  { id: 31, type: 'mcq', question: "Identify the mistake: 'Although' she was very tired, 'but' she tried to finish her homework before going to bed.", options: ["Although", "but", "tried", "before"], answer: 1, explain: "Although ... but không dùng cùng lúc", translate: "Kết nối từ" },
  { id: 32, type: 'mcq', question: "Identify the mistake: We should discuss the plan carefully before making the final 'decide'.", options: ["discuss", "carefully", "making", "decide"], answer: 3, explain: "Decide (động từ) → decision (danh từ)", translate: "Lỗi từ loại" },

  // VII. SENTENCE BUILDING (1.0 điểm)
  { id: 33, type: 'mcq', question: "Choose the correct sentence: Since/move/new city / she / not call/old friends/.", options: ["Since she moves to the new city, she didn't called her old friends.", "Since she moved to the new city, she hasn't called her old friends.", "Since she moved to the new city, she didn't call old friends.", "Since she has moved to the new city, she didn't call her old friends."], answer: 1, explain: "Since + quá khứ, hiện tại hoàn thành", translate: "Thì" },
  { id: 34, type: 'mcq', question: "Choose the correct sentence: If/they/not hurry/they/miss/last bus/.", options: ["If they don't hurry, they would miss the last bus.", "If they didn't hurry, they miss the last bus.", "If they don't hurry, they will miss the last bus.", "If they won't hurry, they will miss the last bus."], answer: 2, explain: "Điều kiện loại 1: If + hiện tại, will + V", translate: "Điều kiện" },
  { id: 35, type: 'mcq', question: "Choose the correct sentence: The scientist/who/win/Nobel Prize/ be / our professor/.", options: ["The scientist who winning the Nobel Prize is our professor.", "The scientist, who won Nobel Prize, is our professor.", "The scientist who won the Nobel Prize is our professor.", "The scientist who he won the Nobel Prize is our professor."], answer: 2, explain: "Người: who (won = quá khứ)", translate: "Đại từ quan hệ" },
  { id: 36, type: 'mcq', question: "Choose the correct sentence: My father / used to/take/us/picnic / every Sunday/.", options: ["My father used to take us to the picnic every Sunday.", "My father is used to take us on a picnic every Sunday.", "My father used to taking us to a picnic every Sunday.", "My father used to take us on a picnic every Sunday."], answer: 3, explain: "Used to + V (thói quen cũ)", translate: "Used to" },

  // VIII. SENTENCE REWRITING (1.0 điểm)
  { id: 37, type: 'mcq', question: "He hasn't eaten fast food for two months. -> The last time...", options: ["he has eaten fast food was 2 months ago", "he ate fast food was 2 months ago", "he eats fast food is 2 months ago", "he didn't eat fast food 2 months ago"], answer: 1, explain: "The last time + quá khứ + was + ago", translate: "Chuyển đổi" },
  { id: 38, type: 'mcq', question: " 'Did you travel to Ha Long Bay last summer, Nam?' said Lan. -> Lan asked...", options: ["Nam if he travels to Ha Long Bay the previous summer", "Nam if he had traveled to Ha Long Bay the previous summer", "Nam did he travel to Ha Long Bay the previous summer", "Nam if he traveled to Ha Long Bay last summer"], answer: 1, explain: "Câu gián tiếp: quá khứ hoàn thành", translate: "Gián tiếp" },
  { id: 39, type: 'mcq', question: "The Nile River is longer than all the other rivers in the world. -> No other...", options: ["river is as long as the Nile", "river in the world is longer than the Nile", "river in the world is as long as the Nile", "river is longer than the Nile"], answer: 1, explain: "No other + danh từ + so sánh hơn", translate: "So sánh" },
  { id: 40, type: 'mcq', question: "We plan to visit the city museum next Saturday. -> We are going...", options: ["to visit the city museum next Saturday", "visiting the city museum next Saturday", "visit the city museum next Saturday", "to visiting the city museum next Saturday"], answer: 0, explain: "Be going to + V (tương lai)", translate: "Tương lai" }
];
